export const actiontypes={
    SET_COUNTRY_NAME:'SET_COUNTRY_NAME',
    SET_COUNTRY_LIST:'SET_COUNTRY_LIST',
    SET_TEAM__NAME:'SET_TEAM__NAME',
    SET_TEAM_LIST:'SET_TEAM_LIST',
    SET_SELECTED_PLAYERS:'SET_SELECTED_PLAYERS'
};